name: Dev Stand

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          branch: develop
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "lf-albion-price-dev"
          heroku_email: "shaggydmitrydev@gmail.com"
          usedocker: true
          dontuseforce: true